springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}
  
spring:
  application:
    name: petstoreproductservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${productServiceDbUrl}
    username: ${productServiceDbUsername}
    password: ${productServiceDbPassword}
    azure:
      passwordless-enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            endpoint: https://petstore-demo-vault.vault.azure.net

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
